// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlockDumpList.proto

#ifndef PROTOBUF_BlockDumpList_2eproto__INCLUDED
#define PROTOBUF_BlockDumpList_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class BlockDumpList;
class BlockDumpListDefaultTypeInternal;
extern BlockDumpListDefaultTypeInternal _BlockDumpList_default_instance_;

namespace protobuf_BlockDumpList_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_BlockDumpList_2eproto

// ===================================================================

class BlockDumpList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BlockDumpList) */ {
 public:
  BlockDumpList();
  virtual ~BlockDumpList();

  BlockDumpList(const BlockDumpList& from);

  inline BlockDumpList& operator=(const BlockDumpList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BlockDumpList& default_instance();

  static inline const BlockDumpList* internal_default_instance() {
    return reinterpret_cast<const BlockDumpList*>(
               &_BlockDumpList_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(BlockDumpList* other);

  // implements Message ----------------------------------------------

  inline BlockDumpList* New() const PROTOBUF_FINAL { return New(NULL); }

  BlockDumpList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BlockDumpList& from);
  void MergeFrom(const BlockDumpList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BlockDumpList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes BlockDump = 1;
  int blockdump_size() const;
  void clear_blockdump();
  static const int kBlockDumpFieldNumber = 1;
  const ::std::string& blockdump(int index) const;
  ::std::string* mutable_blockdump(int index);
  void set_blockdump(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_blockdump(int index, ::std::string&& value);
  #endif
  void set_blockdump(int index, const char* value);
  void set_blockdump(int index, const void* value, size_t size);
  ::std::string* add_blockdump();
  void add_blockdump(const ::std::string& value);
  #if LANG_CXX11
  void add_blockdump(::std::string&& value);
  #endif
  void add_blockdump(const char* value);
  void add_blockdump(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& blockdump() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_blockdump();

  // @@protoc_insertion_point(class_scope:BlockDumpList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> blockdump_;
  friend struct protobuf_BlockDumpList_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// BlockDumpList

// repeated bytes BlockDump = 1;
inline int BlockDumpList::blockdump_size() const {
  return blockdump_.size();
}
inline void BlockDumpList::clear_blockdump() {
  blockdump_.Clear();
}
inline const ::std::string& BlockDumpList::blockdump(int index) const {
  // @@protoc_insertion_point(field_get:BlockDumpList.BlockDump)
  return blockdump_.Get(index);
}
inline ::std::string* BlockDumpList::mutable_blockdump(int index) {
  // @@protoc_insertion_point(field_mutable:BlockDumpList.BlockDump)
  return blockdump_.Mutable(index);
}
inline void BlockDumpList::set_blockdump(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:BlockDumpList.BlockDump)
  blockdump_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void BlockDumpList::set_blockdump(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:BlockDumpList.BlockDump)
  blockdump_.Mutable(index)->assign(std::move(value));
}
#endif
inline void BlockDumpList::set_blockdump(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  blockdump_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:BlockDumpList.BlockDump)
}
inline void BlockDumpList::set_blockdump(int index, const void* value, size_t size) {
  blockdump_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:BlockDumpList.BlockDump)
}
inline ::std::string* BlockDumpList::add_blockdump() {
  // @@protoc_insertion_point(field_add_mutable:BlockDumpList.BlockDump)
  return blockdump_.Add();
}
inline void BlockDumpList::add_blockdump(const ::std::string& value) {
  blockdump_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:BlockDumpList.BlockDump)
}
#if LANG_CXX11
inline void BlockDumpList::add_blockdump(::std::string&& value) {
  blockdump_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:BlockDumpList.BlockDump)
}
#endif
inline void BlockDumpList::add_blockdump(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  blockdump_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:BlockDumpList.BlockDump)
}
inline void BlockDumpList::add_blockdump(const void* value, size_t size) {
  blockdump_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:BlockDumpList.BlockDump)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
BlockDumpList::blockdump() const {
  // @@protoc_insertion_point(field_list:BlockDumpList.BlockDump)
  return blockdump_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
BlockDumpList::mutable_blockdump() {
  // @@protoc_insertion_point(field_mutable_list:BlockDumpList.BlockDump)
  return &blockdump_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BlockDumpList_2eproto__INCLUDED
