// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmprimsend.proto

#ifndef PROTOBUF_mmprimsend_2eproto__INCLUDED
#define PROTOBUF_mmprimsend_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "mmbuiltintype.pb.h"
#include "mmbase.pb.h"
// @@protoc_insertion_point(includes)
namespace micromsg {
class AdditionalContactList;
class AdditionalContactListDefaultTypeInternal;
extern AdditionalContactListDefaultTypeInternal _AdditionalContactList_default_instance_;
class BaseRequest;
class BaseRequestDefaultTypeInternal;
extern BaseRequestDefaultTypeInternal _BaseRequest_default_instance_;
class BaseResponse;
class BaseResponseDefaultTypeInternal;
extern BaseResponseDefaultTypeInternal _BaseResponse_default_instance_;
class BindEmailRequest;
class BindEmailRequestDefaultTypeInternal;
extern BindEmailRequestDefaultTypeInternal _BindEmailRequest_default_instance_;
class BindEmailResponse;
class BindEmailResponseDefaultTypeInternal;
extern BindEmailResponseDefaultTypeInternal _BindEmailResponse_default_instance_;
class BuiltinIP;
class BuiltinIPDefaultTypeInternal;
extern BuiltinIPDefaultTypeInternal _BuiltinIP_default_instance_;
class BuiltinIPList;
class BuiltinIPListDefaultTypeInternal;
extern BuiltinIPListDefaultTypeInternal _BuiltinIPList_default_instance_;
class CDNDnsInfo;
class CDNDnsInfoDefaultTypeInternal;
extern CDNDnsInfoDefaultTypeInternal _CDNDnsInfo_default_instance_;
class ChatRoomMemberData;
class ChatRoomMemberDataDefaultTypeInternal;
extern ChatRoomMemberDataDefaultTypeInternal _ChatRoomMemberData_default_instance_;
class ChatRoomMemberInfo;
class ChatRoomMemberInfoDefaultTypeInternal;
extern ChatRoomMemberInfoDefaultTypeInternal _ChatRoomMemberInfo_default_instance_;
class CmdItem;
class CmdItemDefaultTypeInternal;
extern CmdItemDefaultTypeInternal _CmdItem_default_instance_;
class CmdList;
class CmdListDefaultTypeInternal;
extern CmdListDefaultTypeInternal _CmdList_default_instance_;
class CustomizedInfo;
class CustomizedInfoDefaultTypeInternal;
extern CustomizedInfoDefaultTypeInternal _CustomizedInfo_default_instance_;
class DelMemberReq;
class DelMemberReqDefaultTypeInternal;
extern DelMemberReqDefaultTypeInternal _DelMemberReq_default_instance_;
class DelMemberResp;
class DelMemberRespDefaultTypeInternal;
extern DelMemberRespDefaultTypeInternal _DelMemberResp_default_instance_;
class DisturbSetting;
class DisturbSettingDefaultTypeInternal;
extern DisturbSettingDefaultTypeInternal _DisturbSetting_default_instance_;
class DisturbTimeSpan;
class DisturbTimeSpanDefaultTypeInternal;
extern DisturbTimeSpanDefaultTypeInternal _DisturbTimeSpan_default_instance_;
class GetLocationRequest;
class GetLocationRequestDefaultTypeInternal;
extern GetLocationRequestDefaultTypeInternal _GetLocationRequest_default_instance_;
class GetLocationResponse;
class GetLocationResponseDefaultTypeInternal;
extern GetLocationResponseDefaultTypeInternal _GetLocationResponse_default_instance_;
class GmailInfo;
class GmailInfoDefaultTypeInternal;
extern GmailInfoDefaultTypeInternal _GmailInfo_default_instance_;
class GmailList;
class GmailListDefaultTypeInternal;
extern GmailListDefaultTypeInternal _GmailList_default_instance_;
class HardDevice;
class HardDeviceDefaultTypeInternal;
extern HardDeviceDefaultTypeInternal _HardDevice_default_instance_;
class Host;
class HostDefaultTypeInternal;
extern HostDefaultTypeInternal _Host_default_instance_;
class HostList;
class HostListDefaultTypeInternal;
extern HostListDefaultTypeInternal _HostList_default_instance_;
class LinkedinContactItem;
class LinkedinContactItemDefaultTypeInternal;
extern LinkedinContactItemDefaultTypeInternal _LinkedinContactItem_default_instance_;
class MemberReq;
class MemberReqDefaultTypeInternal;
extern MemberReqDefaultTypeInternal _MemberReq_default_instance_;
class MemberResp;
class MemberRespDefaultTypeInternal;
extern MemberRespDefaultTypeInternal _MemberResp_default_instance_;
class MicroMsgRequestNew;
class MicroMsgRequestNewDefaultTypeInternal;
extern MicroMsgRequestNewDefaultTypeInternal _MicroMsgRequestNew_default_instance_;
class MicroMsgResponseNew;
class MicroMsgResponseNewDefaultTypeInternal;
extern MicroMsgResponseNewDefaultTypeInternal _MicroMsgResponseNew_default_instance_;
class ModContact;
class ModContactDefaultTypeInternal;
extern ModContactDefaultTypeInternal _ModContact_default_instance_;
class ModUserInfo;
class ModUserInfoDefaultTypeInternal;
extern ModUserInfoDefaultTypeInternal _ModUserInfo_default_instance_;
class NetworkControl;
class NetworkControlDefaultTypeInternal;
extern NetworkControlDefaultTypeInternal _NetworkControl_default_instance_;
class PatternLockInfo;
class PatternLockInfoDefaultTypeInternal;
extern PatternLockInfoDefaultTypeInternal _PatternLockInfo_default_instance_;
class PluginKey;
class PluginKeyDefaultTypeInternal;
extern PluginKeyDefaultTypeInternal _PluginKey_default_instance_;
class PluginKeyList;
class PluginKeyListDefaultTypeInternal;
extern PluginKeyListDefaultTypeInternal _PluginKeyList_default_instance_;
class PositionInfo;
class PositionInfoDefaultTypeInternal;
extern PositionInfoDefaultTypeInternal _PositionInfo_default_instance_;
class RoomInfo;
class RoomInfoDefaultTypeInternal;
extern RoomInfoDefaultTypeInternal _RoomInfo_default_instance_;
class SKBuiltinBuffer_t;
class SKBuiltinBuffer_tDefaultTypeInternal;
extern SKBuiltinBuffer_tDefaultTypeInternal _SKBuiltinBuffer_t_default_instance_;
class SKBuiltinChar_t;
class SKBuiltinChar_tDefaultTypeInternal;
extern SKBuiltinChar_tDefaultTypeInternal _SKBuiltinChar_t_default_instance_;
class SKBuiltinDouble64_t;
class SKBuiltinDouble64_tDefaultTypeInternal;
extern SKBuiltinDouble64_tDefaultTypeInternal _SKBuiltinDouble64_t_default_instance_;
class SKBuiltinFloat32_t;
class SKBuiltinFloat32_tDefaultTypeInternal;
extern SKBuiltinFloat32_tDefaultTypeInternal _SKBuiltinFloat32_t_default_instance_;
class SKBuiltinInt16_t;
class SKBuiltinInt16_tDefaultTypeInternal;
extern SKBuiltinInt16_tDefaultTypeInternal _SKBuiltinInt16_t_default_instance_;
class SKBuiltinInt32_t;
class SKBuiltinInt32_tDefaultTypeInternal;
extern SKBuiltinInt32_tDefaultTypeInternal _SKBuiltinInt32_t_default_instance_;
class SKBuiltinInt64_t;
class SKBuiltinInt64_tDefaultTypeInternal;
extern SKBuiltinInt64_tDefaultTypeInternal _SKBuiltinInt64_t_default_instance_;
class SKBuiltinInt8_t;
class SKBuiltinInt8_tDefaultTypeInternal;
extern SKBuiltinInt8_tDefaultTypeInternal _SKBuiltinInt8_t_default_instance_;
class SKBuiltinString_t;
class SKBuiltinString_tDefaultTypeInternal;
extern SKBuiltinString_tDefaultTypeInternal _SKBuiltinString_t_default_instance_;
class SKBuiltinUchar_t;
class SKBuiltinUchar_tDefaultTypeInternal;
extern SKBuiltinUchar_tDefaultTypeInternal _SKBuiltinUchar_t_default_instance_;
class SKBuiltinUint16_t;
class SKBuiltinUint16_tDefaultTypeInternal;
extern SKBuiltinUint16_tDefaultTypeInternal _SKBuiltinUint16_t_default_instance_;
class SKBuiltinUint32_t;
class SKBuiltinUint32_tDefaultTypeInternal;
extern SKBuiltinUint32_tDefaultTypeInternal _SKBuiltinUint32_t_default_instance_;
class SKBuiltinUint64_t;
class SKBuiltinUint64_tDefaultTypeInternal;
extern SKBuiltinUint64_tDefaultTypeInternal _SKBuiltinUint64_t_default_instance_;
class SKBuiltinUint8_t;
class SKBuiltinUint8_tDefaultTypeInternal;
extern SKBuiltinUint8_tDefaultTypeInternal _SKBuiltinUint8_t_default_instance_;
class SafeDevice;
class SafeDeviceDefaultTypeInternal;
extern SafeDeviceDefaultTypeInternal _SafeDevice_default_instance_;
class SafeDeviceList;
class SafeDeviceListDefaultTypeInternal;
extern SafeDeviceListDefaultTypeInternal _SafeDeviceList_default_instance_;
class SendMsgRequestNew;
class SendMsgRequestNewDefaultTypeInternal;
extern SendMsgRequestNewDefaultTypeInternal _SendMsgRequestNew_default_instance_;
class SendMsgResponseNew;
class SendMsgResponseNewDefaultTypeInternal;
extern SendMsgResponseNewDefaultTypeInternal _SendMsgResponseNew_default_instance_;
class ShakeSyncRequest;
class ShakeSyncRequestDefaultTypeInternal;
extern ShakeSyncRequestDefaultTypeInternal _ShakeSyncRequest_default_instance_;
class ShakeSyncResponse;
class ShakeSyncResponseDefaultTypeInternal;
extern ShakeSyncResponseDefaultTypeInternal _ShakeSyncResponse_default_instance_;
class ShowStyleKey;
class ShowStyleKeyDefaultTypeInternal;
extern ShowStyleKeyDefaultTypeInternal _ShowStyleKey_default_instance_;
class SnsUserInfo;
class SnsUserInfoDefaultTypeInternal;
extern SnsUserInfoDefaultTypeInternal _SnsUserInfo_default_instance_;
class StyleKeyVal;
class StyleKeyValDefaultTypeInternal;
extern StyleKeyValDefaultTypeInternal _StyleKeyVal_default_instance_;
class UserInfoExt;
class UserInfoExtDefaultTypeInternal;
extern UserInfoExtDefaultTypeInternal _UserInfoExt_default_instance_;
}  // namespace micromsg

namespace micromsg {

namespace protobuf_mmprimsend_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_mmprimsend_2eproto

// ===================================================================

class MicroMsgRequestNew : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:micromsg.MicroMsgRequestNew) */ {
 public:
  MicroMsgRequestNew();
  virtual ~MicroMsgRequestNew();

  MicroMsgRequestNew(const MicroMsgRequestNew& from);

  inline MicroMsgRequestNew& operator=(const MicroMsgRequestNew& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MicroMsgRequestNew& default_instance();

  static inline const MicroMsgRequestNew* internal_default_instance() {
    return reinterpret_cast<const MicroMsgRequestNew*>(
               &_MicroMsgRequestNew_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MicroMsgRequestNew* other);

  // implements Message ----------------------------------------------

  inline MicroMsgRequestNew* New() const PROTOBUF_FINAL { return New(NULL); }

  MicroMsgRequestNew* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MicroMsgRequestNew& from);
  void MergeFrom(const MicroMsgRequestNew& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MicroMsgRequestNew* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string Content = 2;
  bool has_content() const;
  void clear_content();
  static const int kContentFieldNumber = 2;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // optional string MsgSource = 6;
  bool has_msgsource() const;
  void clear_msgsource();
  static const int kMsgSourceFieldNumber = 6;
  const ::std::string& msgsource() const;
  void set_msgsource(const ::std::string& value);
  #if LANG_CXX11
  void set_msgsource(::std::string&& value);
  #endif
  void set_msgsource(const char* value);
  void set_msgsource(const char* value, size_t size);
  ::std::string* mutable_msgsource();
  ::std::string* release_msgsource();
  void set_allocated_msgsource(::std::string* msgsource);

  // required .micromsg.SKBuiltinString_t ToUserName = 1;
  bool has_tousername() const;
  void clear_tousername();
  static const int kToUserNameFieldNumber = 1;
  const ::micromsg::SKBuiltinString_t& tousername() const;
  ::micromsg::SKBuiltinString_t* mutable_tousername();
  ::micromsg::SKBuiltinString_t* release_tousername();
  void set_allocated_tousername(::micromsg::SKBuiltinString_t* tousername);

  // required uint32 Type = 3;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // required uint32 CreateTime = 4;
  bool has_createtime() const;
  void clear_createtime();
  static const int kCreateTimeFieldNumber = 4;
  ::google::protobuf::uint32 createtime() const;
  void set_createtime(::google::protobuf::uint32 value);

  // required uint32 ClientMsgId = 5;
  bool has_clientmsgid() const;
  void clear_clientmsgid();
  static const int kClientMsgIdFieldNumber = 5;
  ::google::protobuf::uint32 clientmsgid() const;
  void set_clientmsgid(::google::protobuf::uint32 value);

  // optional uint32 CtrlBit = 7;
  bool has_ctrlbit() const;
  void clear_ctrlbit();
  static const int kCtrlBitFieldNumber = 7;
  ::google::protobuf::uint32 ctrlbit() const;
  void set_ctrlbit(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:micromsg.MicroMsgRequestNew)
 private:
  void set_has_tousername();
  void clear_has_tousername();
  void set_has_content();
  void clear_has_content();
  void set_has_type();
  void clear_has_type();
  void set_has_createtime();
  void clear_has_createtime();
  void set_has_clientmsgid();
  void clear_has_clientmsgid();
  void set_has_msgsource();
  void clear_has_msgsource();
  void set_has_ctrlbit();
  void clear_has_ctrlbit();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  ::google::protobuf::internal::ArenaStringPtr msgsource_;
  ::micromsg::SKBuiltinString_t* tousername_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 createtime_;
  ::google::protobuf::uint32 clientmsgid_;
  ::google::protobuf::uint32 ctrlbit_;
  friend struct protobuf_mmprimsend_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SendMsgRequestNew : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:micromsg.SendMsgRequestNew) */ {
 public:
  SendMsgRequestNew();
  virtual ~SendMsgRequestNew();

  SendMsgRequestNew(const SendMsgRequestNew& from);

  inline SendMsgRequestNew& operator=(const SendMsgRequestNew& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SendMsgRequestNew& default_instance();

  static inline const SendMsgRequestNew* internal_default_instance() {
    return reinterpret_cast<const SendMsgRequestNew*>(
               &_SendMsgRequestNew_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SendMsgRequestNew* other);

  // implements Message ----------------------------------------------

  inline SendMsgRequestNew* New() const PROTOBUF_FINAL { return New(NULL); }

  SendMsgRequestNew* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SendMsgRequestNew& from);
  void MergeFrom(const SendMsgRequestNew& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SendMsgRequestNew* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .micromsg.MicroMsgRequestNew List = 2;
  int list_size() const;
  void clear_list();
  static const int kListFieldNumber = 2;
  const ::micromsg::MicroMsgRequestNew& list(int index) const;
  ::micromsg::MicroMsgRequestNew* mutable_list(int index);
  ::micromsg::MicroMsgRequestNew* add_list();
  ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgRequestNew >*
      mutable_list();
  const ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgRequestNew >&
      list() const;

  // required uint32 Count = 1;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 1;
  ::google::protobuf::uint32 count() const;
  void set_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:micromsg.SendMsgRequestNew)
 private:
  void set_has_count();
  void clear_has_count();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgRequestNew > list_;
  ::google::protobuf::uint32 count_;
  friend struct protobuf_mmprimsend_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MicroMsgResponseNew : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:micromsg.MicroMsgResponseNew) */ {
 public:
  MicroMsgResponseNew();
  virtual ~MicroMsgResponseNew();

  MicroMsgResponseNew(const MicroMsgResponseNew& from);

  inline MicroMsgResponseNew& operator=(const MicroMsgResponseNew& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MicroMsgResponseNew& default_instance();

  static inline const MicroMsgResponseNew* internal_default_instance() {
    return reinterpret_cast<const MicroMsgResponseNew*>(
               &_MicroMsgResponseNew_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(MicroMsgResponseNew* other);

  // implements Message ----------------------------------------------

  inline MicroMsgResponseNew* New() const PROTOBUF_FINAL { return New(NULL); }

  MicroMsgResponseNew* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MicroMsgResponseNew& from);
  void MergeFrom(const MicroMsgResponseNew& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MicroMsgResponseNew* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .micromsg.SKBuiltinString_t ToUserName = 2;
  bool has_tousername() const;
  void clear_tousername();
  static const int kToUserNameFieldNumber = 2;
  const ::micromsg::SKBuiltinString_t& tousername() const;
  ::micromsg::SKBuiltinString_t* mutable_tousername();
  ::micromsg::SKBuiltinString_t* release_tousername();
  void set_allocated_tousername(::micromsg::SKBuiltinString_t* tousername);

  // required int32 Ret = 1;
  bool has_ret() const;
  void clear_ret();
  static const int kRetFieldNumber = 1;
  ::google::protobuf::int32 ret() const;
  void set_ret(::google::protobuf::int32 value);

  // required uint32 MsgId = 3;
  bool has_msgid() const;
  void clear_msgid();
  static const int kMsgIdFieldNumber = 3;
  ::google::protobuf::uint32 msgid() const;
  void set_msgid(::google::protobuf::uint32 value);

  // required uint32 ClientMsgId = 4;
  bool has_clientmsgid() const;
  void clear_clientmsgid();
  static const int kClientMsgIdFieldNumber = 4;
  ::google::protobuf::uint32 clientmsgid() const;
  void set_clientmsgid(::google::protobuf::uint32 value);

  // required uint32 CreateTime = 5;
  bool has_createtime() const;
  void clear_createtime();
  static const int kCreateTimeFieldNumber = 5;
  ::google::protobuf::uint32 createtime() const;
  void set_createtime(::google::protobuf::uint32 value);

  // required uint32 ServerTime = 6;
  bool has_servertime() const;
  void clear_servertime();
  static const int kServerTimeFieldNumber = 6;
  ::google::protobuf::uint32 servertime() const;
  void set_servertime(::google::protobuf::uint32 value);

  // required uint32 Type = 7;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 7;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // optional uint64 NewMsgId = 8;
  bool has_newmsgid() const;
  void clear_newmsgid();
  static const int kNewMsgIdFieldNumber = 8;
  ::google::protobuf::uint64 newmsgid() const;
  void set_newmsgid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:micromsg.MicroMsgResponseNew)
 private:
  void set_has_ret();
  void clear_has_ret();
  void set_has_tousername();
  void clear_has_tousername();
  void set_has_msgid();
  void clear_has_msgid();
  void set_has_clientmsgid();
  void clear_has_clientmsgid();
  void set_has_createtime();
  void clear_has_createtime();
  void set_has_servertime();
  void clear_has_servertime();
  void set_has_type();
  void clear_has_type();
  void set_has_newmsgid();
  void clear_has_newmsgid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::micromsg::SKBuiltinString_t* tousername_;
  ::google::protobuf::int32 ret_;
  ::google::protobuf::uint32 msgid_;
  ::google::protobuf::uint32 clientmsgid_;
  ::google::protobuf::uint32 createtime_;
  ::google::protobuf::uint32 servertime_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint64 newmsgid_;
  friend struct protobuf_mmprimsend_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SendMsgResponseNew : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:micromsg.SendMsgResponseNew) */ {
 public:
  SendMsgResponseNew();
  virtual ~SendMsgResponseNew();

  SendMsgResponseNew(const SendMsgResponseNew& from);

  inline SendMsgResponseNew& operator=(const SendMsgResponseNew& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SendMsgResponseNew& default_instance();

  static inline const SendMsgResponseNew* internal_default_instance() {
    return reinterpret_cast<const SendMsgResponseNew*>(
               &_SendMsgResponseNew_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(SendMsgResponseNew* other);

  // implements Message ----------------------------------------------

  inline SendMsgResponseNew* New() const PROTOBUF_FINAL { return New(NULL); }

  SendMsgResponseNew* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SendMsgResponseNew& from);
  void MergeFrom(const SendMsgResponseNew& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SendMsgResponseNew* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .micromsg.MicroMsgResponseNew List = 3;
  int list_size() const;
  void clear_list();
  static const int kListFieldNumber = 3;
  const ::micromsg::MicroMsgResponseNew& list(int index) const;
  ::micromsg::MicroMsgResponseNew* mutable_list(int index);
  ::micromsg::MicroMsgResponseNew* add_list();
  ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgResponseNew >*
      mutable_list();
  const ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgResponseNew >&
      list() const;

  // required .micromsg.BaseResponse BaseResponse = 1;
  bool has_baseresponse() const;
  void clear_baseresponse();
  static const int kBaseResponseFieldNumber = 1;
  const ::micromsg::BaseResponse& baseresponse() const;
  ::micromsg::BaseResponse* mutable_baseresponse();
  ::micromsg::BaseResponse* release_baseresponse();
  void set_allocated_baseresponse(::micromsg::BaseResponse* baseresponse);

  // required uint32 Count = 2;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 2;
  ::google::protobuf::uint32 count() const;
  void set_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:micromsg.SendMsgResponseNew)
 private:
  void set_has_baseresponse();
  void clear_has_baseresponse();
  void set_has_count();
  void clear_has_count();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgResponseNew > list_;
  ::micromsg::BaseResponse* baseresponse_;
  ::google::protobuf::uint32 count_;
  friend struct protobuf_mmprimsend_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MicroMsgRequestNew

// required .micromsg.SKBuiltinString_t ToUserName = 1;
inline bool MicroMsgRequestNew::has_tousername() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MicroMsgRequestNew::set_has_tousername() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MicroMsgRequestNew::clear_has_tousername() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MicroMsgRequestNew::clear_tousername() {
  if (tousername_ != NULL) tousername_->::micromsg::SKBuiltinString_t::Clear();
  clear_has_tousername();
}
inline const ::micromsg::SKBuiltinString_t& MicroMsgRequestNew::tousername() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgRequestNew.ToUserName)
  return tousername_ != NULL ? *tousername_
                         : *::micromsg::SKBuiltinString_t::internal_default_instance();
}
inline ::micromsg::SKBuiltinString_t* MicroMsgRequestNew::mutable_tousername() {
  set_has_tousername();
  if (tousername_ == NULL) {
    tousername_ = new ::micromsg::SKBuiltinString_t;
  }
  // @@protoc_insertion_point(field_mutable:micromsg.MicroMsgRequestNew.ToUserName)
  return tousername_;
}
inline ::micromsg::SKBuiltinString_t* MicroMsgRequestNew::release_tousername() {
  // @@protoc_insertion_point(field_release:micromsg.MicroMsgRequestNew.ToUserName)
  clear_has_tousername();
  ::micromsg::SKBuiltinString_t* temp = tousername_;
  tousername_ = NULL;
  return temp;
}
inline void MicroMsgRequestNew::set_allocated_tousername(::micromsg::SKBuiltinString_t* tousername) {
  delete tousername_;
  tousername_ = tousername;
  if (tousername) {
    set_has_tousername();
  } else {
    clear_has_tousername();
  }
  // @@protoc_insertion_point(field_set_allocated:micromsg.MicroMsgRequestNew.ToUserName)
}

// optional string Content = 2;
inline bool MicroMsgRequestNew::has_content() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MicroMsgRequestNew::set_has_content() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MicroMsgRequestNew::clear_has_content() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MicroMsgRequestNew::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_content();
}
inline const ::std::string& MicroMsgRequestNew::content() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgRequestNew.Content)
  return content_.GetNoArena();
}
inline void MicroMsgRequestNew::set_content(const ::std::string& value) {
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgRequestNew.Content)
}
#if LANG_CXX11
inline void MicroMsgRequestNew::set_content(::std::string&& value) {
  set_has_content();
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:micromsg.MicroMsgRequestNew.Content)
}
#endif
inline void MicroMsgRequestNew::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:micromsg.MicroMsgRequestNew.Content)
}
inline void MicroMsgRequestNew::set_content(const char* value, size_t size) {
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:micromsg.MicroMsgRequestNew.Content)
}
inline ::std::string* MicroMsgRequestNew::mutable_content() {
  set_has_content();
  // @@protoc_insertion_point(field_mutable:micromsg.MicroMsgRequestNew.Content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MicroMsgRequestNew::release_content() {
  // @@protoc_insertion_point(field_release:micromsg.MicroMsgRequestNew.Content)
  clear_has_content();
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MicroMsgRequestNew::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    set_has_content();
  } else {
    clear_has_content();
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:micromsg.MicroMsgRequestNew.Content)
}

// required uint32 Type = 3;
inline bool MicroMsgRequestNew::has_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MicroMsgRequestNew::set_has_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MicroMsgRequestNew::clear_has_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MicroMsgRequestNew::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 MicroMsgRequestNew::type() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgRequestNew.Type)
  return type_;
}
inline void MicroMsgRequestNew::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgRequestNew.Type)
}

// required uint32 CreateTime = 4;
inline bool MicroMsgRequestNew::has_createtime() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MicroMsgRequestNew::set_has_createtime() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MicroMsgRequestNew::clear_has_createtime() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MicroMsgRequestNew::clear_createtime() {
  createtime_ = 0u;
  clear_has_createtime();
}
inline ::google::protobuf::uint32 MicroMsgRequestNew::createtime() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgRequestNew.CreateTime)
  return createtime_;
}
inline void MicroMsgRequestNew::set_createtime(::google::protobuf::uint32 value) {
  set_has_createtime();
  createtime_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgRequestNew.CreateTime)
}

// required uint32 ClientMsgId = 5;
inline bool MicroMsgRequestNew::has_clientmsgid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MicroMsgRequestNew::set_has_clientmsgid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MicroMsgRequestNew::clear_has_clientmsgid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MicroMsgRequestNew::clear_clientmsgid() {
  clientmsgid_ = 0u;
  clear_has_clientmsgid();
}
inline ::google::protobuf::uint32 MicroMsgRequestNew::clientmsgid() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgRequestNew.ClientMsgId)
  return clientmsgid_;
}
inline void MicroMsgRequestNew::set_clientmsgid(::google::protobuf::uint32 value) {
  set_has_clientmsgid();
  clientmsgid_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgRequestNew.ClientMsgId)
}

// optional string MsgSource = 6;
inline bool MicroMsgRequestNew::has_msgsource() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MicroMsgRequestNew::set_has_msgsource() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MicroMsgRequestNew::clear_has_msgsource() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MicroMsgRequestNew::clear_msgsource() {
  msgsource_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msgsource();
}
inline const ::std::string& MicroMsgRequestNew::msgsource() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgRequestNew.MsgSource)
  return msgsource_.GetNoArena();
}
inline void MicroMsgRequestNew::set_msgsource(const ::std::string& value) {
  set_has_msgsource();
  msgsource_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgRequestNew.MsgSource)
}
#if LANG_CXX11
inline void MicroMsgRequestNew::set_msgsource(::std::string&& value) {
  set_has_msgsource();
  msgsource_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:micromsg.MicroMsgRequestNew.MsgSource)
}
#endif
inline void MicroMsgRequestNew::set_msgsource(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_msgsource();
  msgsource_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:micromsg.MicroMsgRequestNew.MsgSource)
}
inline void MicroMsgRequestNew::set_msgsource(const char* value, size_t size) {
  set_has_msgsource();
  msgsource_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:micromsg.MicroMsgRequestNew.MsgSource)
}
inline ::std::string* MicroMsgRequestNew::mutable_msgsource() {
  set_has_msgsource();
  // @@protoc_insertion_point(field_mutable:micromsg.MicroMsgRequestNew.MsgSource)
  return msgsource_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MicroMsgRequestNew::release_msgsource() {
  // @@protoc_insertion_point(field_release:micromsg.MicroMsgRequestNew.MsgSource)
  clear_has_msgsource();
  return msgsource_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MicroMsgRequestNew::set_allocated_msgsource(::std::string* msgsource) {
  if (msgsource != NULL) {
    set_has_msgsource();
  } else {
    clear_has_msgsource();
  }
  msgsource_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msgsource);
  // @@protoc_insertion_point(field_set_allocated:micromsg.MicroMsgRequestNew.MsgSource)
}

// optional uint32 CtrlBit = 7;
inline bool MicroMsgRequestNew::has_ctrlbit() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MicroMsgRequestNew::set_has_ctrlbit() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MicroMsgRequestNew::clear_has_ctrlbit() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MicroMsgRequestNew::clear_ctrlbit() {
  ctrlbit_ = 0u;
  clear_has_ctrlbit();
}
inline ::google::protobuf::uint32 MicroMsgRequestNew::ctrlbit() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgRequestNew.CtrlBit)
  return ctrlbit_;
}
inline void MicroMsgRequestNew::set_ctrlbit(::google::protobuf::uint32 value) {
  set_has_ctrlbit();
  ctrlbit_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgRequestNew.CtrlBit)
}

// -------------------------------------------------------------------

// SendMsgRequestNew

// required uint32 Count = 1;
inline bool SendMsgRequestNew::has_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SendMsgRequestNew::set_has_count() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SendMsgRequestNew::clear_has_count() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SendMsgRequestNew::clear_count() {
  count_ = 0u;
  clear_has_count();
}
inline ::google::protobuf::uint32 SendMsgRequestNew::count() const {
  // @@protoc_insertion_point(field_get:micromsg.SendMsgRequestNew.Count)
  return count_;
}
inline void SendMsgRequestNew::set_count(::google::protobuf::uint32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:micromsg.SendMsgRequestNew.Count)
}

// repeated .micromsg.MicroMsgRequestNew List = 2;
inline int SendMsgRequestNew::list_size() const {
  return list_.size();
}
inline void SendMsgRequestNew::clear_list() {
  list_.Clear();
}
inline const ::micromsg::MicroMsgRequestNew& SendMsgRequestNew::list(int index) const {
  // @@protoc_insertion_point(field_get:micromsg.SendMsgRequestNew.List)
  return list_.Get(index);
}
inline ::micromsg::MicroMsgRequestNew* SendMsgRequestNew::mutable_list(int index) {
  // @@protoc_insertion_point(field_mutable:micromsg.SendMsgRequestNew.List)
  return list_.Mutable(index);
}
inline ::micromsg::MicroMsgRequestNew* SendMsgRequestNew::add_list() {
  // @@protoc_insertion_point(field_add:micromsg.SendMsgRequestNew.List)
  return list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgRequestNew >*
SendMsgRequestNew::mutable_list() {
  // @@protoc_insertion_point(field_mutable_list:micromsg.SendMsgRequestNew.List)
  return &list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgRequestNew >&
SendMsgRequestNew::list() const {
  // @@protoc_insertion_point(field_list:micromsg.SendMsgRequestNew.List)
  return list_;
}

// -------------------------------------------------------------------

// MicroMsgResponseNew

// required int32 Ret = 1;
inline bool MicroMsgResponseNew::has_ret() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MicroMsgResponseNew::set_has_ret() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MicroMsgResponseNew::clear_has_ret() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MicroMsgResponseNew::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 MicroMsgResponseNew::ret() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgResponseNew.Ret)
  return ret_;
}
inline void MicroMsgResponseNew::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgResponseNew.Ret)
}

// required .micromsg.SKBuiltinString_t ToUserName = 2;
inline bool MicroMsgResponseNew::has_tousername() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MicroMsgResponseNew::set_has_tousername() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MicroMsgResponseNew::clear_has_tousername() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MicroMsgResponseNew::clear_tousername() {
  if (tousername_ != NULL) tousername_->::micromsg::SKBuiltinString_t::Clear();
  clear_has_tousername();
}
inline const ::micromsg::SKBuiltinString_t& MicroMsgResponseNew::tousername() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgResponseNew.ToUserName)
  return tousername_ != NULL ? *tousername_
                         : *::micromsg::SKBuiltinString_t::internal_default_instance();
}
inline ::micromsg::SKBuiltinString_t* MicroMsgResponseNew::mutable_tousername() {
  set_has_tousername();
  if (tousername_ == NULL) {
    tousername_ = new ::micromsg::SKBuiltinString_t;
  }
  // @@protoc_insertion_point(field_mutable:micromsg.MicroMsgResponseNew.ToUserName)
  return tousername_;
}
inline ::micromsg::SKBuiltinString_t* MicroMsgResponseNew::release_tousername() {
  // @@protoc_insertion_point(field_release:micromsg.MicroMsgResponseNew.ToUserName)
  clear_has_tousername();
  ::micromsg::SKBuiltinString_t* temp = tousername_;
  tousername_ = NULL;
  return temp;
}
inline void MicroMsgResponseNew::set_allocated_tousername(::micromsg::SKBuiltinString_t* tousername) {
  delete tousername_;
  tousername_ = tousername;
  if (tousername) {
    set_has_tousername();
  } else {
    clear_has_tousername();
  }
  // @@protoc_insertion_point(field_set_allocated:micromsg.MicroMsgResponseNew.ToUserName)
}

// required uint32 MsgId = 3;
inline bool MicroMsgResponseNew::has_msgid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MicroMsgResponseNew::set_has_msgid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MicroMsgResponseNew::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MicroMsgResponseNew::clear_msgid() {
  msgid_ = 0u;
  clear_has_msgid();
}
inline ::google::protobuf::uint32 MicroMsgResponseNew::msgid() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgResponseNew.MsgId)
  return msgid_;
}
inline void MicroMsgResponseNew::set_msgid(::google::protobuf::uint32 value) {
  set_has_msgid();
  msgid_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgResponseNew.MsgId)
}

// required uint32 ClientMsgId = 4;
inline bool MicroMsgResponseNew::has_clientmsgid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MicroMsgResponseNew::set_has_clientmsgid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MicroMsgResponseNew::clear_has_clientmsgid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MicroMsgResponseNew::clear_clientmsgid() {
  clientmsgid_ = 0u;
  clear_has_clientmsgid();
}
inline ::google::protobuf::uint32 MicroMsgResponseNew::clientmsgid() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgResponseNew.ClientMsgId)
  return clientmsgid_;
}
inline void MicroMsgResponseNew::set_clientmsgid(::google::protobuf::uint32 value) {
  set_has_clientmsgid();
  clientmsgid_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgResponseNew.ClientMsgId)
}

// required uint32 CreateTime = 5;
inline bool MicroMsgResponseNew::has_createtime() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MicroMsgResponseNew::set_has_createtime() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MicroMsgResponseNew::clear_has_createtime() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MicroMsgResponseNew::clear_createtime() {
  createtime_ = 0u;
  clear_has_createtime();
}
inline ::google::protobuf::uint32 MicroMsgResponseNew::createtime() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgResponseNew.CreateTime)
  return createtime_;
}
inline void MicroMsgResponseNew::set_createtime(::google::protobuf::uint32 value) {
  set_has_createtime();
  createtime_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgResponseNew.CreateTime)
}

// required uint32 ServerTime = 6;
inline bool MicroMsgResponseNew::has_servertime() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MicroMsgResponseNew::set_has_servertime() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MicroMsgResponseNew::clear_has_servertime() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MicroMsgResponseNew::clear_servertime() {
  servertime_ = 0u;
  clear_has_servertime();
}
inline ::google::protobuf::uint32 MicroMsgResponseNew::servertime() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgResponseNew.ServerTime)
  return servertime_;
}
inline void MicroMsgResponseNew::set_servertime(::google::protobuf::uint32 value) {
  set_has_servertime();
  servertime_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgResponseNew.ServerTime)
}

// required uint32 Type = 7;
inline bool MicroMsgResponseNew::has_type() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MicroMsgResponseNew::set_has_type() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MicroMsgResponseNew::clear_has_type() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MicroMsgResponseNew::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 MicroMsgResponseNew::type() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgResponseNew.Type)
  return type_;
}
inline void MicroMsgResponseNew::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgResponseNew.Type)
}

// optional uint64 NewMsgId = 8;
inline bool MicroMsgResponseNew::has_newmsgid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MicroMsgResponseNew::set_has_newmsgid() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MicroMsgResponseNew::clear_has_newmsgid() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MicroMsgResponseNew::clear_newmsgid() {
  newmsgid_ = GOOGLE_ULONGLONG(0);
  clear_has_newmsgid();
}
inline ::google::protobuf::uint64 MicroMsgResponseNew::newmsgid() const {
  // @@protoc_insertion_point(field_get:micromsg.MicroMsgResponseNew.NewMsgId)
  return newmsgid_;
}
inline void MicroMsgResponseNew::set_newmsgid(::google::protobuf::uint64 value) {
  set_has_newmsgid();
  newmsgid_ = value;
  // @@protoc_insertion_point(field_set:micromsg.MicroMsgResponseNew.NewMsgId)
}

// -------------------------------------------------------------------

// SendMsgResponseNew

// required .micromsg.BaseResponse BaseResponse = 1;
inline bool SendMsgResponseNew::has_baseresponse() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SendMsgResponseNew::set_has_baseresponse() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SendMsgResponseNew::clear_has_baseresponse() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SendMsgResponseNew::clear_baseresponse() {
  if (baseresponse_ != NULL) baseresponse_->::micromsg::BaseResponse::Clear();
  clear_has_baseresponse();
}
inline const ::micromsg::BaseResponse& SendMsgResponseNew::baseresponse() const {
  // @@protoc_insertion_point(field_get:micromsg.SendMsgResponseNew.BaseResponse)
  return baseresponse_ != NULL ? *baseresponse_
                         : *::micromsg::BaseResponse::internal_default_instance();
}
inline ::micromsg::BaseResponse* SendMsgResponseNew::mutable_baseresponse() {
  set_has_baseresponse();
  if (baseresponse_ == NULL) {
    baseresponse_ = new ::micromsg::BaseResponse;
  }
  // @@protoc_insertion_point(field_mutable:micromsg.SendMsgResponseNew.BaseResponse)
  return baseresponse_;
}
inline ::micromsg::BaseResponse* SendMsgResponseNew::release_baseresponse() {
  // @@protoc_insertion_point(field_release:micromsg.SendMsgResponseNew.BaseResponse)
  clear_has_baseresponse();
  ::micromsg::BaseResponse* temp = baseresponse_;
  baseresponse_ = NULL;
  return temp;
}
inline void SendMsgResponseNew::set_allocated_baseresponse(::micromsg::BaseResponse* baseresponse) {
  delete baseresponse_;
  baseresponse_ = baseresponse;
  if (baseresponse) {
    set_has_baseresponse();
  } else {
    clear_has_baseresponse();
  }
  // @@protoc_insertion_point(field_set_allocated:micromsg.SendMsgResponseNew.BaseResponse)
}

// required uint32 Count = 2;
inline bool SendMsgResponseNew::has_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SendMsgResponseNew::set_has_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SendMsgResponseNew::clear_has_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SendMsgResponseNew::clear_count() {
  count_ = 0u;
  clear_has_count();
}
inline ::google::protobuf::uint32 SendMsgResponseNew::count() const {
  // @@protoc_insertion_point(field_get:micromsg.SendMsgResponseNew.Count)
  return count_;
}
inline void SendMsgResponseNew::set_count(::google::protobuf::uint32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:micromsg.SendMsgResponseNew.Count)
}

// repeated .micromsg.MicroMsgResponseNew List = 3;
inline int SendMsgResponseNew::list_size() const {
  return list_.size();
}
inline void SendMsgResponseNew::clear_list() {
  list_.Clear();
}
inline const ::micromsg::MicroMsgResponseNew& SendMsgResponseNew::list(int index) const {
  // @@protoc_insertion_point(field_get:micromsg.SendMsgResponseNew.List)
  return list_.Get(index);
}
inline ::micromsg::MicroMsgResponseNew* SendMsgResponseNew::mutable_list(int index) {
  // @@protoc_insertion_point(field_mutable:micromsg.SendMsgResponseNew.List)
  return list_.Mutable(index);
}
inline ::micromsg::MicroMsgResponseNew* SendMsgResponseNew::add_list() {
  // @@protoc_insertion_point(field_add:micromsg.SendMsgResponseNew.List)
  return list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgResponseNew >*
SendMsgResponseNew::mutable_list() {
  // @@protoc_insertion_point(field_mutable_list:micromsg.SendMsgResponseNew.List)
  return &list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::micromsg::MicroMsgResponseNew >&
SendMsgResponseNew::list() const {
  // @@protoc_insertion_point(field_list:micromsg.SendMsgResponseNew.List)
  return list_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace micromsg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mmprimsend_2eproto__INCLUDED
